### PR TITLE
add rating and toast component

### PR DESCRIPTION
**Pull request by iRohitGaur**

### CODE REVIEW

**Review by humzahasan — APPROVED** [review]
- Good selection of class name
- Good documentation

Looks good to merge!

**Review by varun13169 — APPROVED** [review]
LGTM

**Review by bhushannaikaroskar — APPROVED** [review]
Awesome work Rohit. Looks perfect to merge.

**Review by zoef-yt — APPROVED** [review]
Nice work. Looks good to merge.

**Pull request merged**
